routes/web.php
<?php

use App\Http\Controllers\BookController;
use App\Http\Controllers\DegreeController;
use App\Http\Controllers\SubjectController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });


// Route::get('degrees',[DegreeController::class,'index']);
// Route::get('degrees/create', [DegreeController::class, 'create']);
// Route::get('subjects', [SubjectController::class, 'index']);

Route::resource('books',BookController::class)->name('all','books');
// Route::resource('photos', PhotoController::class);

// Route::get('books', [BookController::class, 'index']);
// Route::get('books/create',[BookController::class,'create']);
// Route::post('books/store', [BookController::class, 'store']);

app/Models/Book.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Book extends Model
{
    use HasFactory;

    protected $fillable = [
        'title',
        'isbn',
        'author',
        'edition'
    ];

}

app/Models/Degree.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Degree extends Model
{
    use HasFactory;
    use SoftDeletes;

    protected $fillable = [
        'title',
        'created_at',
        'updated_at',
        'deleted_at'
    ];

}

app/Models/Subject.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Subject extends Model
{
    use HasFactory;

    use SoftDeletes;

    protected $fillables = [
        'title',
        'degree_id',
        'created_at',
        'updated_at',
        'deleted_at'
    ];

}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/BookController.php
<?php

namespace App\Http\Controllers;

use App\Models\Book;
use Illuminate\Http\Request;

class BookController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $books = Book::all();
        return view('books.index',compact('books'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('books.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
       $ob = new Book();
       $ob->title =$request->title;
       $ob->isbn = $request->isbn;
       $ob->author = $request->author;
       $ob->edition = $request->edition;
       $ob->save();

       return redirect('books')->with('sucess','The Book Successfully added!');


    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function show(Book $book)
    {
        return view('books.show',compact('book'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function edit(Book $book)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Book $book)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function destroy(Book $book)
    {
        //
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/DegreeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Degree;

class DegreeController extends Controller
{
    public function index(){
        $degrees = Degree::all();

        foreach ($degrees as $degree) {
            echo $degree->id . " ". $degree->title;
            echo "<hr>";
        }

    }


    public function create(){
        // $abc = Degree::create(
        //     ['title' => 'Networking']
        // );

        $abc = new Degree();
        $abc->title = 'MCS';
        $abc->save();

        dd($abc);
    }
}

app/Http/Controllers/HomeController.php
<?php


class HomeController extends Controller
{
    
}

app/Http/Controllers/SubjectController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Subject;

class SubjectController extends Controller
{
    public function index(){
        $degrees = Subject::all();

        foreach ($degrees as $degree) {
            echo $degree->id . " ". $degree->title;
            echo "<hr>";
        }

    }

}

resources/views/books/create.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container">
  <h2>Vertical (basic) form</h2>
  <form method="POST" action="{{route('books.store')}}">
    {{ csrf_field() }}
    <div class="form-group">
      <label for="email">Title:</label>
      <input type="text" class="form-control" placeholder="Enter email" name="title">
    </div>

    <div class="form-group">
      <label for="email">ISBN:</label>
      <input type="text" class="form-control" placeholder="Enter email" name="isbn">
    </div>
    <div class="form-group">
      <label for="email">Author:</label>
      <input type="text" class="form-control" placeholder="Enter email" name="author">
    </div>

    <div class="form-group">
      <label for="email">Edition:</label>
      <input type="text" class="form-control" placeholder="Enter email" name="edition">
    </div>


    <button type="submit" class="btn btn-default">Submit</button>
  </form>
</div>

</body>
</html>

resources/views/books/index.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container">
  <h2>Striped Rows</h2>
  <p>The .table-striped class adds zebra-stripes to a table:</p>
{{ session()->get('sucess') }}


  <table class="table table-striped">
    <thead>
      <tr>
        <th>Title</th>
        <th>ISBN</th>
        <th>Author</th>
        <th>Edition</th>
      </tr>
    </thead>
    <tbody>
        @foreach ($books as $book)
        <tr>
            <td>{{$book->title}}</td>
            <td>{{$book->isbn}}</td>
            <td>{{$book->author}}</td>
            <td>{{$book->edition}}</td>
            <td>
                <a href="{{route('books.show',$book->id)}}">Show</a>
            </td>
        </tr>
        @endforeach
    </tbody>
  </table>
</div>

</body>
</html>

resources/views/books/show.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container">
  <h2>Striped Rows</h2>
  <p>The .table-striped class adds zebra-stripes to a table:</p>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Title</th>
        <th>ISBN</th>
        <th>Author</th>
        <th>Edition</th>
      </tr>
    </thead>
    <tbody>
        <tr>
            <td>{{$book->title}}</td>
            <td>{{$book->isbn}}</td>
            <td>{{$book->author}}</td>
            <td>{{$book->edition}}</td>
        </tr>
    </tbody>
  </table>
</div>

</body>
</html>